[package]
name = "game_payment"
version = "1.0.0"
published-at = "0x0" # This will be filled in after publishing

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "main" }

[addresses]
game = "0x0" # This will be replaced with your package address after publishing
